# model: "deepcoder:latest"
# model: "devstral:latest"
model: "deepseek-r1:14b"
langsmith:
  enable: false
  tracing: "true"
  endpoint: https://api.smith.langchain.com
  apikey: 
  project: 
steps:
  fix_tautologies: true
  fix_infinite_loop: true

